<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoSwshRng.Core\AutoSwshRng.Core.csproj" />
    <ProjectReference Include="..\..\third_party\EasyCon\src\EasyCon.Device\EasyCon.Device.csproj" />
    <ProjectReference Include="..\..\third_party\EasyCon\src\EasyCon.Script\EasyCon.Script.csproj" />
    <ProjectReference Include="..\..\third_party\owoow\owoow.Core\owoow.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\third_party\EasyCon\src\EasyCon2.UI.Common\Resources\Docs\scriptdoc.txt"
                      LogicalName="AutoSwshRng.Upstream.Resources.EasyCon.scriptdoc.txt" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
