<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoSwshRng.Core\AutoSwshRng.Core.csproj" />
    <ProjectReference Include="..\AutoSwshRng.Upstream\AutoSwshRng.Upstream.csproj" />
    <ProjectReference Include="..\..\third_party\EasyCon\src\EasyCon2\EasyCon2.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
