"""Python task coordination and automation primitives."""

from .stage_executor import AutomationStageExecutor, StageOutcome, StageResult
from .models import (
    AutomationConfig,
    AutomationEvent,
    AutomationPhase,
    AutomationRunResult,
    AutomationRunStatus,
    SeedEpochSummary,
)
from .runner import AutomationNeedsAttention, AutomationRunner
from .seed_observer import (
    AnimationFramePhase,
    AnimationFrameScore,
    SeedBitObservation,
    SeedObserver,
    SeedSequenceObservation,
    SystemClock,
)
from .replay import (
    ReplayActionSegment,
    ReplayFrameRef,
    ReplayFrameSource,
    ReplayValidationError,
    VirtualClock,
    load_replay_manifest,
)
from .evidence import (
    EvidenceStore,
    EvidenceValidationError,
    can_start_formal,
    initialize_manifest,
    validate_manifest,
)
from .scene_guard import (
    SceneAssessment,
    SceneGuard,
    SceneGuardError,
    SceneObservation,
)
from .simulation import SimulationDevicePort, SimulationFault, SimulationTaskLease
from .boundary import (
    BoundaryAdjustment,
    BoundaryApplicationLedger,
    solve_trigger_advance,
    update_boundary_adjustment,
)
from .feedback import (
    CalibrationSample,
    FeedbackArchiveStore,
    FeedbackController,
    FeedbackDecision,
    FeedbackError,
    TimingSensitivityEstimator,
    TimingUpdate,
    attribute_calibration_sample,
)
from .retry_workflow import RetryWorkflow, RetryWorkflowError, RetryWorkflowResult
from .save_commit import (
    SaveCommit,
    SaveCommitError,
    SaveCommitStore,
    SaveReceipt,
)
from .npc_calibration import (
    CalibrationAccountingEntry,
    NpcCalibrationCache,
    NpcCalibrationContext,
    NpcCalibrationError,
    NpcCalibrationNeedsAttention,
    NpcCalibrationResult,
    NpcCalibrationSession,
    ProbeCandidate,
    ProbeDesign,
    ProbeExperiment,
    build_probe_candidates,
)
from .desktop_calibration_diagnostic import DesktopNpcCalibrationDiagnostic
from .attempt_planner import (
    AttemptPlanResult,
    AttemptPlanner,
    AttemptPlanningError,
    AttemptPlanningNeedsAttention,
    AttemptPlanningSettings,
    PlanningTarget,
)
from .attempt_execution import (
    AttemptActionPort,
    AttemptExecutionCoordinator,
    AttemptExecutionError,
    AttemptExecutionNeedsAttention,
    AttemptExecutionResult,
    AttemptExecutionSettings,
    AttemptExecutionStatus,
    AttemptStageScripts,
    EcsAttemptActionPort,
    RelocationResult,
    SeedRelocator,
)
from .attempt_workflow import (
    M2M4AttemptCoordinator,
    M2M4ClosedLoopCoordinator,
    M2M4ClosedLoopResult,
    M2M4WorkflowError,
    M2M4WorkflowNeedsAttention,
    NpcCalibrationOutcome,
)
from .replay_attempts import ReplayAttemptActionPort
from .capture_attempt import (
    CaptureActionPort,
    CaptureAttemptCoordinator,
    CaptureAttemptCancelled,
    CaptureAttemptError,
    CaptureAttemptResult,
    ReplayCaptureActionPort,
    ReplayCaptureFixture,
    ReplayCaptureStep,
)
from .capture_workflow import (
    CaptureEvent,
    CaptureEvidenceError,
    CapturePhase,
    CaptureWorkflow,
    EncounterAttemptSnapshot,
    EntityIdentityResult,
    FieldObservation,
    FieldRead,
    ObservationStatus,
    RosterMember,
    TargetVerificationResult,
    aggregate_field_reads,
    identify_new_roster_entity,
    verify_capture_target,
)

__all__ = [
    "AnimationFramePhase",
    "AnimationFrameScore",
    "BoundaryAdjustment",
    "BoundaryApplicationLedger",
    "AutomationConfig",
    "AutomationEvent",
    "AutomationNeedsAttention",
    "AutomationPhase",
    "AutomationRunResult",
    "AutomationRunner",
    "AutomationRunStatus",
    "AutomationStageExecutor",
    "EvidenceStore",
    "EvidenceValidationError",
    "ReplayActionSegment",
    "ReplayFrameRef",
    "ReplayFrameSource",
    "ReplayValidationError",
    "SceneAssessment",
    "SceneGuard",
    "SceneGuardError",
    "SceneObservation",
    "SaveCommit",
    "SaveCommitError",
    "SaveCommitStore",
    "SaveReceipt",
    "SimulationDevicePort",
    "SimulationFault",
    "SimulationTaskLease",
    "SeedBitObservation",
    "SeedObserver",
    "SeedEpochSummary",
    "SeedSequenceObservation",
    "StageOutcome",
    "StageResult",
    "SystemClock",
    "VirtualClock",
    "can_start_formal",
    "initialize_manifest",
    "load_replay_manifest",
    "solve_trigger_advance",
    "update_boundary_adjustment",
    "CalibrationSample",
    "FeedbackArchiveStore",
    "FeedbackController",
    "FeedbackDecision",
    "FeedbackError",
    "TimingSensitivityEstimator",
    "TimingUpdate",
    "attribute_calibration_sample",
    "RetryWorkflow",
    "RetryWorkflowError",
    "RetryWorkflowResult",
    "validate_manifest",
]

__all__ += [
    "AttemptPlanResult",
    "AttemptPlanner",
    "AttemptPlanningError",
    "AttemptPlanningNeedsAttention",
    "AttemptPlanningSettings",
    "CalibrationAccountingEntry",
    "NpcCalibrationCache",
    "NpcCalibrationContext",
    "NpcCalibrationError",
    "NpcCalibrationNeedsAttention",
    "NpcCalibrationResult",
    "NpcCalibrationSession",
    "ProbeCandidate",
    "ProbeDesign",
    "ProbeExperiment",
    "PlanningTarget",
    "AttemptActionPort",
    "AttemptExecutionCoordinator",
    "AttemptExecutionError",
    "AttemptExecutionNeedsAttention",
    "AttemptExecutionResult",
    "AttemptExecutionSettings",
    "AttemptExecutionStatus",
    "AttemptStageScripts",
    "EcsAttemptActionPort",
    "RelocationResult",
    "SeedRelocator",
    "M2M4AttemptCoordinator",
    "M2M4ClosedLoopCoordinator",
    "M2M4ClosedLoopResult",
    "M2M4WorkflowError",
    "M2M4WorkflowNeedsAttention",
    "NpcCalibrationOutcome",
    "DesktopNpcCalibrationDiagnostic",
    "ReplayAttemptActionPort",
    "CaptureActionPort",
    "CaptureAttemptCoordinator",
    "CaptureAttemptCancelled",
    "CaptureAttemptError",
    "CaptureAttemptResult",
    "ReplayCaptureActionPort",
    "ReplayCaptureFixture",
    "ReplayCaptureStep",
    "CaptureEvent",
    "CaptureEvidenceError",
    "CapturePhase",
    "CaptureWorkflow",
    "EncounterAttemptSnapshot",
    "EntityIdentityResult",
    "FieldObservation",
    "FieldRead",
    "ObservationStatus",
    "RosterMember",
    "TargetVerificationResult",
    "aggregate_field_reads",
    "identify_new_roster_entity",
    "verify_capture_target",
    "build_probe_candidates",
]
