"""Synthetic desktop entry point for the offline NPC calibration workflow."""
from __future__ import annotations

import threading
import uuid

from ..backend import PROTOCOL_VERSION
from ..localization import BASELINE
from .desktop_calculator import CalculatorCancelled, DesktopJsonCalculator
from .npc_calibration import (
    NpcCalibrationContext,
    NpcCalibrationSession,
    ProbeExperiment,
    build_probe_candidates,
)


class DesktopNpcCalibrationDiagnostic:
    """Run a fully synthetic training and independent-validation exercise.

    The fixture observations are generated by the configured calculator for a
    known synthetic interference model. This exercises the calibration
    workflow and report path; it is not an independent algorithm or hardware
    validation.
    """

    KNOWN_SYNTHETIC_INTERFERENCE_ADVANCES = 3

    def __init__(self, backend, *, run_id: str, context_revision: int,
                 game="Shield", scenario_id="desktop-synthetic-diagnostic"):
        if not isinstance(run_id, str) or not run_id.strip():
            raise ValueError("run_id is required")
        if isinstance(context_revision, bool) or not isinstance(context_revision, int) or context_revision < 0:
            raise ValueError("context_revision must be a non-negative integer")
        if not isinstance(game, str) or not game.strip():
            raise ValueError("game is required")
        if not isinstance(scenario_id, str) or not scenario_id.strip():
            raise ValueError("scenario_id is required")
        self.calculator = DesktopJsonCalculator(backend)
        self.run_id = run_id
        self.epoch_id = f"{run_id}:npc-diagnostic"
        self.context_revision = context_revision
        self.game = game
        self.scenario_id = scenario_id
        self.cancel_event = threading.Event()

    def run(self):
        known_model = build_probe_candidates(
            interferenceAdvances=[self.KNOWN_SYNTHETIC_INTERFERENCE_ADVANCES],
        )[0]
        actions = ({"kind": "interference"},)
        experiments = []
        for role, indices in (("training", range(1, 4)), ("validation", range(21, 23))):
            for index in indices:
                self._check_cancel()
                seed0 = f"{index:016x}"
                seed1 = f"{index + 10_000:016x}"
                response = self.calculator.execute(self._observation_request(
                    seed0, seed1, known_model, actions,
                ), self.cancel_event)
                data = response.get("data")
                rows = data.get("candidates") if isinstance(data, dict) else None
                if (not isinstance(rows, list) or len(rows) != 1 or not isinstance(rows[0], dict)
                        or rows[0].get("candidateId") != known_model.candidate_id
                        or rows[0].get("predictedAdvances") != self.KNOWN_SYNTHETIC_INTERFERENCE_ADVANCES
                        or not isinstance(rows[0].get("predictedEndState"), dict)):
                    raise ValueError("calculator returned an invalid synthetic probe observation")
                observed_state = rows[0]["predictedEndState"]
                experiments.append(ProbeExperiment(
                    experiment_id=f"{self.run_id}-{role}-{index}",
                    seed0=seed0,
                    seed1=seed1,
                    observed_seed0=observed_state.get("seed0"),
                    observed_seed1=observed_state.get("seed1"),
                    probe_actions=actions,
                    source_kind="synthetic",
                    observation_advances=0,
                    observed_advances=self.KNOWN_SYNTHETIC_INTERFERENCE_ADVANCES,
                    action_log=({
                        "kind": "synthetic_probe_fixture",
                        "knownModelAdvances": self.KNOWN_SYNTHETIC_INTERFERENCE_ADVANCES,
                        "scenarioId": self.scenario_id,
                    },),
                ))

        context = NpcCalibrationContext(
            game=self.game,
            region="synthetic-diagnostic",
            subregion="interference-probe",
            route_version="desktop-synthetic-v1",
            weather="synthetic",
            menu_action="synthetic-interference-probe",
            hold_direction=False,
            start_position={"sourceKind": "synthetic", "scenarioId": self.scenario_id},
            camera_state={"sourceKind": "synthetic"},
            lead_setup={"sourceKind": "synthetic"},
            algorithm_commit=BASELINE["algorithm"]["commit"],
        )
        session = NpcCalibrationSession(
            context=context,
            candidates=build_probe_candidates(interferenceAdvances=range(6)),
            calculator=self.calculator,
            run_id=self.run_id,
            epoch_id=self.epoch_id,
            context_revision=self.context_revision,
            cancel_event=self.cancel_event,
            minimum_training_experiments=3,
            minimum_validation_experiments=2,
        )
        return session.calibrate(experiments[:3], experiments[3:])

    def cancel(self):
        self.cancel_event.set()

    def _observation_request(self, seed0, seed1, candidate, actions):
        return {
            "operation": "calibration.probe.evaluate",
            "protocolVersion": PROTOCOL_VERSION,
            "requestId": uuid.uuid4().hex,
            "runId": self.run_id,
            "epochId": self.epoch_id,
            "contextRevision": self.context_revision,
            "seed0": seed0,
            "seed1": seed1,
            "sourceKind": "synthetic",
            "evidenceIds": [],
            "probeActions": [dict(action) for action in actions],
            "probeCandidates": [candidate.to_protocol()],
        }

    def _check_cancel(self):
        if self.cancel_event.is_set():
            raise CalculatorCancelled("NPC calibration diagnostic was cancelled")
